### ISSUE TITLE
student_controller_spec is not consistent with the rest of the tests

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/rails-create-action-lab#5]
I'd like to add that you don't have to change these specs per say but if you want the pattern for params to be { student: { first_name: 'Sam', last_name: 'Wise' } } then the Fill In test for capybara for the form will be looking for only last_name not student[last_name].  I wonder what Learn.co's defacto standard is for params.  should we always nest the data?  and if so it would be nice if there was more consistency with it across some labs where possible.  Thank you.

### As it is now with this pattern the student object will be nil.
```ruby
# ./spec/controllers/student_controller_spec.rb
  describe "POST create" do
    context "with valid attributes" do
      it "creates a new student" do
        expect{
          post :create, { :student => { :first_name => "Sam", :last_name => "Smith" } }
        }.to change(Student,:count).by(1)
      end
      
      it "redirects to the new student" do
        post :create, { :student => { :first_name => "Sam", :last_name => "Smith" } }
        expect(response).to redirect_to Student.last
      end
    end
  end
```

### with these changes the spec is consistent with whats expected to work with the integration tests.
```ruby
require 'rails_helper'

describe StudentsController do

  describe "POST create" do
    context "with valid attributes" do
      it "creates a new student" do
        expect{
          post :create, { :first_name => "Sam", :last_name => "Smith" }
        }.to change(Student,:count).by(1)
      end

      it "redirects to the new student" do
        post :create, { :first_name => "Sam", :last_name => "Smith" }
        expect(response).to redirect_to Student.last
      end
    end
  end

end
```

**Comment by pletcher** [comment]
In general, the convention is to shallowly nest parameters, so the spec is all right as is. (This is so that, with larger applications, the client doesn't need to send up an unreadable blob of parameters -- instead, we get some lightweight quasi-namespacing.) 

There will be some variation in different labs due to different writers and priorities (e.g., making the lab easy for students at a given stage of the curriculum to understand), but more consistency might be in the pipeline.

The problem with the solution branch here (which your issue pointed out) is that the tests pass when they shouldn't because there are no validations either on the students table in the db or on the Student model. I'll fix that.

**Comment by pletcher** [comment]
Hm, it looks like I have to take back a bit of what I said. It's true that convention usually nests the params -- Rails form helpers will do this for you -- but this lab doesn't use form helpers. The spec is wrong, and you're right, we should change it.
